apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config
  namespace: roy-dev

data:
  DB_HOST: "roydb.czmyicasgaga.ap-southeast-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "roydb"
  DB_USER: "royuser"
  PORT: "4000"
  NODE_ENV: "production"