apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-autoscaler
rules:
- apiGroups: [""]
  resources: ["pods","services","replicationcontrollers","persistentvolumeclaims","persistentvolumes","nodes","namespaces","endpoints"]
  verbs: ["get","list","watch"]

- apiGroups: ["apps"]
  resources: ["replicasets","statefulsets","daemonsets","deployments"]
  verbs: ["get","list","watch"]

- apiGroups: ["extensions"]
  resources: ["replicasets","daemonsets"]
  verbs: ["get","list","watch"]

- apiGroups: ["batch","extensions"]
  resources: ["jobs","cronjobs"]
  verbs: ["get","list","watch"]

- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses","csinodes","csidrivers","csistoragecapacities"]
  verbs: ["get","list","watch"]

- apiGroups: [""]
  resources: ["events","endpoints"]
  verbs: ["create","patch"]

- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-autoscaler
subjects:
- kind: ServiceAccount
  name: cluster-autoscaler
  namespace: kube-system